=== lunar-logan/stunning-spoon/values/values.dtd
<?xml version="1.0"?>
        <!ELEMENT values (string*, string-array*)>
        <!ELEMENT string (#PCDATA)>
        <!ELEMENT string-array (item*)>
        <!ELEMENT item (#PCDATA)>
        <!ATTLIST string name CDATA #REQUIRED>
        <!ATTLIST string-array name CDATA #REQUIRED>

=== lunar-logan/stunning-spoon/values/values.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE values SYSTEM "values.dtd">
<values>
    <string name="vocab_dir">vocab</string>
    <string name="parser_model_path">E:\\Coding\\Java Related\\stanford-parser\\stanford-parser-full-2015-04-20\\edu\\stanford\\nlp\\models\\parser\\nndep\\english_UD.gz
    </string>
    <string name="tagger_model_path">E:\\Coding\\Java Related\\stanford-parser\\stanford-parser-full-2015-04-20\\edu\\stanford\\nlp\\models\\pos-tagger\\english-left3words\\english-left3words-distsim.tagger
    </string>
    <string name="pcfg_parser_model_path">
        E:\Coding\Java Related\stanford-parser\stanford-parser-full-2015-04-20\edu\stanford\nlp\models\lexparser\englishPCFG.ser.gz
    </string>
    <string name="test_data_dir">data</string>
    <string name="test_dir">test</string>
    <string name="test_out_dir">test_out</string>
    <string name="hello_world">Hello World</string>
    <string-array name="planets">
        <item>Mercury</item>
        <item>Venus</item>
        <item>Earth</item>
        <item>Mars</item>
        <item>Jupitor</item>
        <item>Saturn</item>
        <item>Uranus</item>
        <item>Naptune</item>
        <item>Pluto*</item>
        <item>Planet X</item>
    </string-array>
</values>
